### ISSUE TITLE
今日话题怎么过啊

### ISSUE THREAD

**Issue by heimaobaifanfan** [bc0042/sheep-solver#11]
大佬。今日话题怎么过啊，，今天终于过了每日挑战了，今日话题有没有接口啊，，之前一直用的您的https://github.com/eruobing/SheepASheepV2这个，但是今天开始每日挑战一直报错。

**Comment by bc0042** [comment]
你发的是另外一个大佬的项目，现在好像已经删了，我的这个需要懂一点点编程基础，多看看，看试试

**Comment by heimaobaifanfan** [comment]
大佬，问一下每日话题，
获取matchInfo 
node util/get topic

获取map数据
node util/get map

开始挑战
node auto-test-topic 

提交 
 node util/get t_join 2 加入右边（这一步是不是必须的，一直出错，说是不能修改，我在手机游戏里面已经选过边了。{ err_code: 10004, err_msg: '', data: 'cannot change side err' }
2022-11-05T11:01:15.956Z）

 提交话题 node util/send game2.json topic
（一直会出现这个错误，其实上一步挑战后已经保存到game2.json中的，但是还是下面这个错误，是不是要等一会儿执行这个命令。
gametype: topic
{ err_code: 28001, err_msg: '', data: '' }
skin name: undefined）

 这个顺序有问题吗？还有执行挑战后出现保存game2.json后是不是表示有解？但是执行提交后有时候每日挑战还是不成功。。

**Comment by Caipto** [comment]
node util/get t_join 2，如果你小程序已经选过了，这步不需要，就算有这步，也不影响你的结果提交。

**Comment by Caipto** [comment]
要不你等个1-2分钟再提交？

**Comment by heimaobaifanfan** [comment]
> 要不你等个1-2分钟再提交？

这个顺序是没有问题的把，话题的最后一步提交话题 node util/send game2.json topic用这个？

**Comment by Caipto** [comment]
> > 要不你等个1-2分钟再提交？
> 
> 这个顺序是没有问题的把，话题的最后一步提交话题 node util/send game2.json topic用这个？
你的选择左边还是右边

**Comment by heimaobaifanfan** [comment]
> 

大佬。我是在小程序选的右边。如果没有选是不是在提交话题钱用node util/get t_join 2

然后在用 node util/send game2.json topic

刚才我听您的，储存到game2后等了一会儿，提交反正成功了，不知道这个要等几分钟合适，非常感谢。、
