### ISSUE TITLE
今天是不是失效了

### ISSUE THREAD

**Issue by lslswin** [bc0042/sheep-solver#12]

**Comment by Caipto** [comment]
没有啊

**Comment by lslswin** [comment]
可是我今天运行的时候报错了，昨天都还好好的

**Comment by lslswin** [comment]
![image](https://user-images.githubusercontent.com/116090781/201246093-6d84a9bd-e8ae-4eb5-9360-ddd56810a44a.png)

**Comment by bc0042** [comment]
> ![image](https://user-images.githubusercontent.com/116090781/201246093-6d84a9bd-e8ae-4eb5-9360-ddd56810a44a.png)

token失效了，重新弄一个

**Comment by heimaobaifanfan** [comment]
大佬，是不是再没有更新算法呀，还是以前的吗？感觉现在的怎么出结果这么快，连续好几天，都是五分钟内出的。

**Comment by bc0042** [comment]
> 大佬，是不是再没有更新算法呀，还是以前的吗？感觉现在的怎么出结果这么快，连续好几天，都是五分钟内出的。

是很久没更新过了，这个东西本身就有运气成分，说明你RP比较好

**Comment by heimaobaifanfan** [comment]
大佬，今天羊更新了圈养模式，挑战下线了，跪求大佬再更新一下。

**Comment by bc0042** [comment]
这游戏感觉已经凉了，懒得搞了

**Comment by heimaobaifanfan** [comment]
没有凉呀，哥，。您有时间更新一下呗。。不过话说回来，用了那么多解法，还是你的这个速度最快，其他的都能解四五个小时，
