### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by heimaobaifanfan** [bc0042/sheep-solver#14]
虽然大佬不准备更新了，但是还是很感谢大佬的一键式加入羊群，既简单又方便，主要还省心。希望大佬工作顺利、多多发财、

**Comment by bc0042** [comment]
你可以研究一下，其实把话题模式改成羊圈模式很简单的，估计改动的代码不超过10行

**Comment by heimaobaifanfan** [comment]
> 

哈哈，我的代码从学校出来就还给老师了，这都过了快十年了，您的代码我看都看不懂，
