### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by 499753506** [bc0042/sheep-solver#15]
我能获取羊圈地图的资源，也可以跑出结果，但是最后提交是报错的 err_code: 28001，我只改了util/get.js的少部分代码，麻烦大佬指导一下

**Comment by 499753506** [comment]
现在回到话题了，还是报错28001，我是重新下载了代码

**Comment by bc0042** [comment]
> 我能获取羊圈地图的资源，也可以跑出结果，但是最后提交是报错的 err_code: 28001，我只改了util/get.js的少部分代码，麻烦大佬指导一下

羊圈模式的话，send.js也需要改，gameType不一样，提交结果的接口也不一样

**Comment by bc0042** [comment]
> 现在回到话题了，还是报错28001，我是重新下载了代码

应该是代码还有bug, 在某些特殊情况下会导致步骤有问题，重新换图跑吧

**Comment by 351535126** [comment]
> > 现在回到话题了，还是报错28001，我是重新下载了代码
> 
> 应该是代号还有bug，在某些特殊情况下会导致步骤有问题，重新换图跑吧

能更新一下嘛，大佬。

**Comment by 351535126** [comment]
地图加密了，如何能把从接口获取地图改为缓存获取呢

**Comment by bc0042** [comment]
#18 地图需要解码
