### ISSUE TITLE
真的很奇怪 今天关卡明明已经step1通过，node step2-out 2成功了，上传node until/send game2.jason回馈err-code 28001了

### ISSUE THREAD

**Issue by Caipto** [bc0042/sheep-solver#4]
真的很奇怪 今天关卡明明已经step1通过，node step2-out 2成功了，上传node until/send game2.jason回馈err-code 28001了

**Comment by bc0042** [comment]
test分支应该修复了，你试一下

**Comment by Caipto** [comment]
> test分支应该修复了，你试一下

还是28001

**Comment by bc0042** [comment]
可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 
或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑

**Comment by Caipto** [comment]
> 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑

我不理解 删除之后在执行直接报错

**Comment by Caipto** [comment]
> 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑

还是不行，哎 就是无法提交 28001

**Comment by bc0042** [comment]
> > 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑
> 
> 还是不行，哎 就是无法提交 28001

要不新建个目录重新clone，不行的话我也不知道了

**Comment by Caipto** [comment]
> > > 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑
> > 
> > 
> > 还是不行，哎 就是无法提交 28001
> 
> 要不新建个目录重新clone，不行的话我也不知道了

有没有一种可能 排序出了问题 排序需要重新改并保存，排序给出来的是从中间为第一步往两边开的

**Comment by Caipto** [comment]
> > > 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑
> > 
> > 
> > 还是不行，哎 就是无法提交 28001
> 
> 要不新建个目录重新clone，不行的话我也不知道了

确实是 我们几个朋友都一起测试过 都是一样的结果 都是反馈不出，28001错误，然后我win10电脑运行话题 替换文件之后 运行跑出结果 上传也是erro 28001

**Comment by Caipto** [comment]
> > > 可能是你提交时间的问题，获取地图到提交结果至少要等一分钟 或者是地图缓存数据的问题，删除data下面的match和map, 重新执行get match和get map, 再跑
> > 
> > 
> > 还是不行，哎 就是无法提交 28001
> 
> 要不新建个目录重新clone，不行的话我也不知道了

运行topic 复制文件之后Error: spawn cp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cp',
  path: 'cp',
  spawnargs: [ 'data/topic', 'data/match' ]就是这个

**Comment by bc0042** [comment]
这个错误是你的环境和我不一样，
你试一下修改auto-test-topic中18行
    let child = spawn('cp', ['data/topic', 'data/match'])
改成
    let child = spawn('copy', ['data/topic', 'data/match', '/y'])

**Comment by Caipto** [comment]
> let child = spawn('copy', ['data/topic', 'data/match', '/y'])

放弃了 还是不行 哎

**Comment by Caipto** [comment]
> 这个错误是你的环境和我不一样， 你试一下修改auto-test-topic中18行 let child = spawn('cp', ['data/topic', 'data/match']) 改成 let child = spawn('copy', ['data/topic', 'data/match', '/y'])

Error: spawn copy ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn copy',
  path: 'copy',
  spawnargs: [ 'data/topic', 'data/match', '/y' ]这个了- -

**Comment by bc0042** [comment]
代码更新了，再试一下，不行我再加你
