### ISSUE TITLE
up请问一下这个复制topic到match是啥意思

### ISSUE THREAD

**Issue by Caipto** [bc0042/sheep-solver#6]
up请问一下这个复制topic到match是啥意思

**Comment by bc0042** [comment]
> up请问一下这个复制topic到match是啥意思

把data目录下topic里的内容复制到match

**Comment by Caipto** [comment]
> > up请问一下这个复制topic到match是啥意思
> 
> 把data目录下topic里的内容复制到match

上传排序应该是倒序吧 但是为啥一直28001呢

**Comment by Caipto** [comment]
> > up请问一下这个复制topic到match是啥意思
> 
> 把data目录下topic里的内容复制到match

您如果方便帮我远程一下，有偿，qq379781385

**Comment by Caipto** [comment]
我在研究一下更新了的

**Comment by Caipto** [comment]
今日最新更新测试，话题可以运行，等等看看能不能提交
